# These are supported funding model platforms

github: [edditdev] # GitHub usernames for sponsorship
custom: ['https://www.paypal.me/yourprofile', 'https://example.com/donate'] # Up to 4 custom sponsorship URLs
